### ISSUE TITLE
Request dates by range

### ISSUE THREAD

**Issue by trevordavis** [awerchniak/viz_osrs#5]
This will require a new Select object in QuerySelector. Since it's possible to provide a LIMIT value in the SQL query that exceeds the number of table entires, we don't have to worry about going over.

The general idea is that we could select day, week, month, year to start. These are the labels, but the associated value is how many hours that is in integer form. We pass this value with an update method (see updateSkills in QuerySelector and QueryCreator), which updates some state on the QueryCreator to set the desired number of hours.

Next we can add a getNumEntries() method of some sort in QuerySelector. This is pretty simple, returning number of hours / queries per hour. That's the number we use when fetching data, e.g. "...LIMIT ${this.getNumEntries()}...".

**Comment by awerchniak** [comment]
MySQL queries allow for comparisons between strings; e.g. you can say:
```
SELECT * from tablename WHERE timestamp > 2020-08-10 00:00:00 AND timestamp < 2020:08-17 00:00:00
```

Therefore, I think that the best way to do this would just be to include `Select` objects in `QuerySelector` for year, month, and date (for now, we can do time later if we want but I'm not sure how useful that would be since the tables don't update very frequently). Then, we can pass these to `QueryCreator` and update the `getQuery` syntax to include this WHERE clause. I don't think we need a LIMIT clause, either (we can make the default start date 1 week ago and end date tomorrow)

**Comment by awerchniak** [comment]
Added in 624ef129d4ef56140beaa889d8d3605e7f2185e7
